const productsData = {
    newProducts: [{

            id: 1,
            name: "Cam Canh",
            image: "../image/cam canh.webp",
            price: 50000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Cam DekoponDekopon",
            image: "../image/cam dekopon.webp",
            price: 80000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Cam Sành",
            image: "../image/cam sành.png",
            price: 30000,
            decrease: 27000,
            discount: "-10%",
        },
        {
            id: 4,
            name: "Dâu Tây",
            image: "../image/dâu tây.jpg",
            price: 400000,
            promotion: "new",
        },

        {
            id: 5,
            name: "Dưa hấu không hạt",
            image: "../image/dưa hấu.jpg",
            price: 22000,
            promotion: "new",
        },
        {
            id: 6,
            name: "Nho Tím không hạthạt",
            image: "../image/nho tím.jpg",
            price: 290000,
            decrease: 261000,
            discount: "-10%",
        },
        {
            id: 7,
            name: "Xoài Thái",
            image: "../image/xoài thái.jpg",
            price: 50000,
            
        },
        {
            id: 8,
            name: "Xoài Thanh Ca",
            image: "../image/xoài thanh ca.jpg",
            price: 400000,
            decrease: 360000,
            discount: "-10%",
        },
   
    ],
    Giaynam: [{

            id: 1,
            name: "Lẳng quà số 1",
            image: "../image/lẳng 1.png",
            price: 490000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Lẳng quà số 2 ",
            image: "../image/lẳng 2.png",
            price: 339000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Lẳng quà số 3",
            image: "../image/lẳng 3.png",
            price: 450000,
            decrease: 405000 ,
            discount: "-10%",
        },
        {
            id: 4,
            name: "Lẳng quà số 4",
            image: "../image/lẳng 4.png",
            price: 340000,
            promotion: "new",
        },

        {
            id: 5,
            name: "Lẳng quà số 5",
            image: "../image/lẳng 5.png",
            price: 3070000,
            promotion: "new",
        },
        {
            id: 6,
            name: "Lẳng quà số 6 ",
            image: "../image/lẳng 6.png",
            price: 2199000,
            decrease: 1729000,
            discount: "-21%",
        },
        {
            id: 7,
            name: "Lẳng quà số 7",
            image: "../image/lẳng 10.jpg",
            price: 550000,
            decrease: 440000,
            discount: "-20%",
        },
        {
            id: 8,
            name: "Lẳng quà số 8",
            image: "../image/lẳng 8.jpg",
            price: 600000,
            decrease: 540000,
            discount: "-10%",
        },

     
    ],
    Giaynu: [{
            id: 1,
            name: "Quả quýt/1kg",
            image: "../image/ip17.jpg",
            price: 40000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Dâu tây nhỏ",
            image: "../image/ip18.jpg",
            price: 100000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Vú sữa lò rènrèn",
            image: "../image/ip19.jpg",
            price: 50000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Cam ngọt",
            image: "../image/ip20.jpg",
            price: 30000,
            decrease: 20000,
            discount: "-10%",
        },
        {
            id: 5,
            name: "Cam Dekopon 22",
            image: "../image/cam dekopon.webp",
            price: 2600000,
         
        },
        {
            id: 6,
            name: "Cam Dekopon 3",
            image: "../image/cam dekopon.webp",
            price: 150000,
          
        },
        {
            id: 7,
            name: "Nho Tím Nhập Khẩu",
            image: "../image/nho tím.jpg",
            price:  290000,
        },
        {
            id: 8,
            name: "Xoài Thanh Ca Loại 1",
            image: "../image/xoài thanh ca.jpg",
            price: 50000,
        },
        // {
        //     id: 9,
        //     name: "Giày Crocs Brooklyn Sandals",
        //     image: "../image/ss9.png",
        //     price: 1900000,
        //     promotion: "new",
        // },
        // {
        //     id: 10,
        //     name: "Giày Đế Xuồng Nữ Crocs Brooklyn Luxe Cross Strap",
        //     image: "../image/ss10.png",
        //     price: 3690000,
        //     promotion: "new",
        // },
        // {
        //     id: 11,
        //     name: "Giày Đế Xuồng Nữ Crocs Brookly",
        //     image: "../image/ss11.png",
        //     price: 6590000,
        //     promotion: "new",
        // },
        // {
        //     id: 12,
        //     name: "Crocs Stomp Fisherman Sandals",
        //     image: "../image/ss14.jpg",
        //     price: 2790000,
        //     decrease: 1910000,
        //     discount: "-17%",
        // },
        // {
        //     id: 13,
        //     name: "Crocs Pacer Literide 360",
        //     image: "../image/ss15.jpg",
        //     price: 2800000,
        //     promotion: "new",
        // },
        // {
        //     id: 14,
        //     name: "Crocs Baya Platform Sandals",
        //     image: "../image/ss16.jpg",
        //     price: 949000,
        //     promotion: "new",
        // },
        // {
        //     id: 15,
        //     name: "Crocs Mega Crush Clog",
        //     image: "../image/ss11.png",
        //     price: 959000,
        //     promotion: "new",
        // },
        // {
        //     id: 16,
        //     name: "Crocs Brooklyn Upper Low Wedge",
        //     image: "../image/ss7.jpg",
        //     price: 490000,
        //     promotion: "new",
        // },
    ],
    Depnam: [{
            id: 1,
            name: "Lẳng quà số 1",
            image: "../image/lẳng 1.png",
            price: 390000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Lẳng quà số 2",
            image: "../image/lẳng 2.png",
            price: 900000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Lẳng quà số 3",
            image: "../image/lẳng 3.png",
            price: 349000,
    
        },
        {
            id: 4,
            name: "Lẳng quà số 4",
            image: "../image/lẳng 4.png",
            price: 499000,
            promotion: "new",
        },
        {
            id: 5,
            // name: "Dép literide Clog",
            // image: "../image/o5.png",
            // price: 3990000,
            // decrease: 3100000,
            // discount: "-7%",
            name: "Lẳng quà số 1",
            image: "../image/lẳng 1.png",
            price: 390000,
            promotion: "new",
        },
        {
            id: 6,
            // name: "Dép Classic Crocs Sandal",
            // image: "../image/o6.jpg",
            // price: 4490000,
            name: "Lẳng quà số 2",
            image: "../image/lẳng 2.png",
            price: 900000,
            promotion: "new",
        },
        {
            id: 7,
            // name: "Dép Swiftwater Sandal",
            // image: "../image/o7.jpg",
            // price: 3990000,
            name: "Lẳng quà số 3",
            image: "../image/lẳng 3.png",
            price: 349000,
        },
        {
            id: 8,
            // name: "Dép Classic Flip",
            // image: "../image/o8.jpg",
            // price: 360000,
            // decrease: 290000,
            // discount: "-18%",
            name: "Lẳng quà số 4",
            image: "../image/lẳng 4.png",
            price: 499000,
            promotion: "new",
        },
        // {
        //     id: 9,
        //     name: "ODép Bayaband Flip",
        //     image: "../image/o9.jpg",
        //     price: 4580000,
        //     promotion: "new",
        // },
        // {
        //     id: 10,
        //     name: "Dép Classic All-Terrain Clog",
        //     image: "../image/o10.jpg",
        //     price: 220000,
        //     promotion: "new",
        // },
        // {
        //     id: 11,
        //     name: "Dép Literide Pacer",
        //     image: "../image/o11.jpg",
        //     price: 4600000,
        //     promotion: "new",
        // },
        // {
        //     id: 12,
        //     name: "Dép Crocs CitiLane Clog",
        //     image: "../image/o7.png",
        //     price: 3490000,
        //     decrease: 3350000,
        //     discount: "-4%",
        // },
        // {
        //     id: 13,
        //     name: "Dép Classic Lined Clog",
        //     image: "../image/o13.jpg",
        //     price: 1600000,
        //     promotion: "new",
        // },
        // {
        //     id: 14,
        //     name: "Dép Work Clog",
        //     image: "../image/o14.jpg",
        //     price: 299000,
        //     promotion: "new",
        // },
        // {
        //     id: 15,
        //     name: "Dép Swiftwater Sandal",
        //     image: "../image/o8.jpg",
        //     price: 666000,
        //     decrease: 579000,
        //     discount: "-13%",
        // },
        // {
        //     id: 16,
        //     name: "Dép Classic Crocs Sandal",
        //     image: "../image/o11.jpg",
        //     price: 888000,
        //     promotion: "new",
        // },
    ],

    Depnu: [{
            id: 1,
            name: "Cam Sành mùa thu",
            image: "../image/cam sành.png",
            price: 160000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Lẳng quà mùa Thu",
            image: "../image/lẳng 10.jpg",
            price: 990000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Xoài Úc Nhập Khẩu T8",
            image: "../image/xoài úc.jpg",
            price: 90000,
           
        },
        {
            id: 4,
            name: "Nho tím Mỹ ",
            image: "../image/nho tím.jpg",
            price: 299000,
            promotion: "new",
        },
        {
            id: 5,
            name: "Cam sành 101 ",
            image: "../image/cam sành.png",
            price: 160000,
            promotion: "new",
           
        },
        {
            id: 6,
            name: "Lẳng quà mùa Thu 2",
            image: "../image/lẳng 10.jpg",
            price: 990000,
            promotion: "new",
           
        },
        {
            id: 7,
            name: "Xoài Úc Nhập Khẩu ",
            image: "../image/xoài úc.jpg",
            price: 95000,
           
        },
        {
            id: 8,
            name: "Nho tím Hàn Quốc ",
            image: "../image/nho tím.jpg",
            price: 600000,
        
            
        },
        // {
        //     id: 9,
        //     name: "Dép quai ngang Unisex Crocs Classic Slide Citrus",
        //     image: "../image/r9.jpg",
        //     price: 1350000,
        //     promotion: "new",
        // },
        // {
        //     id: 10,
        //     name: "Dép quai ngang Unisex Crocs Classic II Slide Pink Lemonade",
        //     image: "../image/r10.jpg",
        //     price: 2500000,
        //     promotion: "new",
        // },
        // {
        //     id: 11,
        //     name: "Dép quai ngang Unisex Crocs Classic Slide Cerulean Blue",
        //     image: "../image/r1.jpg",
        //     price: 1600000,
        //     promotion: "new",
        // },
        // {
        //     id: 12,
        //     name: "Dép quai ngang Unisex Crocs LiteRide Slide Blush Pink ",
        //     image: "../image/r8.jpg",
        //     price: 5790000,
        //     decrease: 4632000,
        //     discount: "-20%",
        // },
        // {
        //     id: 13,
        //     name: "RDép quai ngang Unisex Crocs Classic II Slide Red",
        //     image: "../image/r7.jpg",
        //     price: 2480000,
        //     promotion: "new",
        // },
        // {
        //     id: 14,
        //     name: "Dép quai ngang Unisex Crocs Baya Slide Camo",
        //     image: "../image/r9.jpg",
        //     price: 1390000,
        //     promotion: "new",
        // },
        // {
        //     id: 15,
        //     name: "Dép quai ngang Unisex Crocs All-Terrain Slide Black/Charcoal",
        //     image: "../image/r2.jpg",
        //     price: 1050000,
        //     decrease: 810000,
        //     discount: "-20%",
        // },
        // {
        //     id: 16,
        //     name: "Dép quai ngang Unisex Crocs Classic Slide Sunshine Yellow",
        //     image: "../image/r10.jpg",
        //     price: 8420000,
        //     promotion: "new",
        // },
    ],
};

const productsData2 = {
    newProducts: [{
            id: 1,
            name: "Xoài Đỏ Ngọc Vân",
            image: "../image/xoài ngọc vân.jpg",
            price: 800000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Mận An Phước",
            image: "../image/mận an phước.jpg",
            price: 45000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Lẳng quà số 4",
            image: "../image/lẳng 4.png",
            price: 450000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Lẳng quà số 2",
            image: "../image/lẳng 2.png",
            price: 800000,
            promotion: "new",
        },
    ],
    popularProduct: [{
            id: 1,
            name: "Lẳng quà số 9",
            image: "../image/lẳng 9.jpg",
            price: 350000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Cam Canh",
            image: "../image/cam canh.webp",
            price: 60000,
        },
        {
            id: 3,
            name: "Dưa hấu khôngg hạt",
            image: "../image/dưa hấu.jpg",
            price: 26000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Lẳng qùa số 10",
            image: "../image/lẳng 9.jpg",
            price: 2350000,
        },
    ],
    discountProduct: [{
            id: 1,
            name: "lẳng quà số 10",
            image: "../image/lẳng 10.jpg",
            price: 1000000,
            decrease: 900000,
            discount: "-10%",
        },
        {
            id: 2,
            name: "Sầu Riêng Ri6",
            image: "../image/ri6.jpg",
            price: 250000,
            decrease: 200000,
            discount: "-20%",
        },
        {
            id: 3,
            name: "Sầu riêng ri6 2",
            image: "../image/ri6.jpg",
            price: 700000,
            decrease: 420000,
            discount: "-40%",
        },
        {
            id: 4,
            name: "Nho tím không hạt",
            image: "../image/nho tím.jpg",
            price: 130000,
            decrease: 115000,
            discount: "-15%",
        },
    ],
};